"""
builders/builder.py
Base Builder class for all output builders.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

from promptosaurus.registry import registry


class Builder:
    """Base class for all builders that generate output configs."""

    _base_files = [
        "agents/core/core-system.md",
        "agents/core/core-conventions.md",
        "agents/core/core-session.md",
    ]

    def build(
        self, output: Path, config: dict[str, Any] | None = None, dry_run: bool = False
    ) -> list[str]:
        """
        Build output configs.

        Args:
            output: Directory to write output into.
            config: Optional configuration dict with template variables.
            dry_run: If True, preview what would be written without touching filesystem.

        Returns:
            List of action strings for display.
        """
        raise NotImplementedError("Subclasses must implement build()")

    @classmethod
    def _build_concatenated(cls, tool_comment: str) -> str:
        """
        Returns the full text of a concatenated rules file.

        tool_comment: first-line comment, e.g. '# .clinerules'
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            tool_comment,
            "# Auto-generated by prompt CLI — edit files in prompts/ then rebuild",
            f"# Last built: {now}",
            "",
        ]

        for label, filename in registry.concat_order:
            try:
                body = registry.prompt_body(filename)
            except FileNotFoundError:
                lines.append(f"## {label} — MISSING: {filename}")
                lines.append("")
                continue

            lines.append("---")
            lines.append(f"## {label}")
            lines.append("")
            lines.append(body.rstrip())
            lines.append("")

        return "\n".join(lines) + "\n"
